### ISSUE TITLE
About adding phpmyadmin to the services. 

### ISSUE THREAD

**Issue by ankit7540** [TRPB/sitepoint-docker-tutorial#1]
What would be a good way to add phpmyadmin to manage the mysql dbs using phpmyadmin to this project.

I tried the following,

`

    mysql:
        image: mariadb:10.5
        restart: always
        environment:
            MYSQL_ROOT_PASSWORD: secret
        volumes:
            - mysql-data:/var/lib/mysql
        ports:
            - "3306:3306"

    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        restart: always
        environment:
            PMA_HOST: mysql
            PMA_USER: root
            PMA_PASSWORD: secret
        ports:
            - "9800:9800"

`

but I cannot see the phpmyadmin interface at `localhost:9800`.

Nice tutotial by the way,. :-)

**Comment by TRPB** [comment]
That should work fine assuming that phpmyadmin/phpmyadmin listens on port 9800 inside the container,  but I'd strongly recommend just using MySQL Workbench, it's a much more competent tool.

**Comment by ankit7540** [comment]
got it, Thanks.
