### ISSUE TITLE
nginx.conf should be default.conf

### ISSUE THREAD

**Issue by Chouchen** [TRPB/sitepoint-docker-tutorial#2]
I tried [this tutorial](https://www.sitepoint.com/docker-php-development-environment/) but kept coming to nginx default page and not the `phpinfo()`'s one.

I corrected it with changing `- ./nginx.conf:/etc/nginx/conf.d/nginx.conf` to `- ./nginx.conf:/etc/nginx/conf.d/default.conf` since nginx create a `default.conf` with almost the same content as your nginx.conf and that seems to override your conf.

It may help to change it in this repo (and maybe the linked article)

**Comment by TRPB** [comment]
Can you post your config? As long as you have `default_server` in your `listen` directive it should override the inbuilt config.

**Comment by Chouchen** [comment]
Well, it's still the same as this repo. I followed the "TL;DR" section of the article. The only modification I did at first was changing the port on the computer side `- "8080:80"` instead of 80:80, but that doesn't alter the fact that nginx is still listening to 80 in the container, right?

When I go into the container with `docker exec -it dev_web_1 bash` I have :
```
root@622d51a42b83:/# ls -al /etc/nginx/conf.d/
total 24
drwxr-xr-x 1 root root 4096 Feb 16 16:08 .
drwxr-xr-x 1 root root 4096 Jan 26 08:58 ..
-rw-r--r-- 1 root root 1093 Feb 16 16:11 default.conf
-rw-rw-r-- 0 1000 1000  333 Feb 16 16:11 nginx.conf
```

But still, it's the nginx index.html file that is displayed when I go to http://localhost:8080. While watching the log, I still see that the root of the server is `/usr/share/nginx/html/`

The only solution I found was to replace the default.conf with the one from this repo, and now it works.

Note that I'm kind of a beginner in docker for development (I used it only for hosting purpose), so it may be an error on my part but I don't see where.

**Comment by TRPB** [comment]
You'll need to either use `http://127.0.0.1` or set `server_name localhost` in the `server` block. The server isn't configured to listen on `localhost` in the tutorial.

**Comment by Chouchen** [comment]
Oh, I forget to mention, I added `server_name localhost;` and it didn't work (and still doesn't :-( ). Anyway, it, now, works with `http://127.0.0.1:8080`. I tried it before with no luck and now it's OK. I don't know what I've changed :/ 

Sorry for the inconvenience
